# advanced_ai_engine.py

import requests


OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:3b"


def classify_query(query):
    q = query.lower()

    if any(x in q for x in ["homeopathic", "homeopathy", "natural", "herbal", "ayurvedic", "holistic"]):
        return "alternative_medicine"
    if any(x in q for x in ["side effect", "side effects", "safety", "safe", "adverse", "risk"]):
        return "safety"
    if any(x in q for x in ["teen", "teenage", "adolescent", "child", "pediatric", "13", "14", "15"]):
        return "pediatric_adolescent"
    if any(x in q for x in ["best", "compare", "better", "most effective", "strongest"]):
        return "treatment_comparison"
    if any(x in q for x in ["women", "woman", "female", "girls", "girl"]):
        return "female_population"
    return "general_evidence"


def build_evidence_grades(evidence_rows):
    graded = []

    for row in evidence_rows:
        relevance = row.get("relevance_score", 0)
        direction = row.get("direction", "Unclear")

        if relevance >= 55:
            grade = "Strong match"
        elif relevance >= 35:
            grade = "Moderate match"
        elif relevance >= 20:
            grade = "Weak match"
        else:
            grade = "Low match"

        graded.append({
            **row,
            "evidence_grade": grade,
            "audit_note": f"Source match: {grade}. Evidence direction: {direction}."
        })

    return graded


def build_claim_audit(query, evidence_rows):
    claims = []
    q = query.lower()

    for row in evidence_rows:
        snippet = row.get("snippet", "")
        snippet_lower = snippet.lower()
        pmid = row.get("pubmed_id", "Unknown")

        if "ritlecitinib" in snippet_lower:
            claims.append({
                "claim": "Ritlecitinib is discussed in the retrieved evidence for alopecia areata.",
                "supported_by": pmid,
                "evidence_excerpt": snippet[:350]
            })

        if "minoxidil" in snippet_lower:
            claims.append({
                "claim": "Minoxidil is discussed in the retrieved evidence for female pattern hair loss or alopecia-related treatment.",
                "supported_by": pmid,
                "evidence_excerpt": snippet[:350]
            })

        if any(x in q for x in ["homeopathic", "homeopathy", "natural", "herbal", "ayurvedic", "holistic"]):
            claims.append({
                "claim": "The retrieved evidence does not directly establish that homeopathic treatment is effective.",
                "supported_by": pmid,
                "evidence_excerpt": snippet[:350]
            })

    return claims[:6]


def build_context(evidence_rows):
    blocks = []

    for row in evidence_rows:
        blocks.append(
            f"PMID: {row.get('pubmed_id', 'Unknown')}\n"
            f"Relevance score: {row.get('relevance_score', 0)}\n"
            f"Evidence grade: {row.get('evidence_grade', 'Unknown')}\n"
            f"Evidence direction: {row.get('direction', 'Unclear')}\n"
            f"Snippet: {row.get('snippet', '')[:350]}"
        )

    return "\n\n---\n\n".join(blocks)


def generate_with_ollama(system_prompt, user_prompt):
    full_prompt = f"""
{system_prompt}

{user_prompt}
"""

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": OLLAMA_MODEL,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": 0.45,
                "top_p": 0.9,
                "num_predict": 120
            }
        },
        timeout=60
    )

    if response.status_code != 200:
        return (
            "Ollama connected, but local generation failed. "
            f"Status code: {response.status_code}. "
            f"Response: {response.text[:500]}"
        )

    data = response.json()
    return data.get("response", "No response generated by Ollama.")


def generate_custom_ai_answer(query, evidence_rows, evidence_direction):
    query_lower = query.lower()

    treatments = []
    findings = []
    safety_points = []
    gaps = []

    for row in evidence_rows:
        snippet = row.get("snippet", "")
        snippet_lower = snippet.lower()
        pmid = row.get("pubmed_id", "Unknown")

        if "ritlecitinib" in snippet_lower and "ritlecitinib" not in treatments:
            treatments.append("ritlecitinib")
        if "minoxidil" in snippet_lower and "minoxidil" not in treatments:
            treatments.append("minoxidil")

        if "hair regrowth" in snippet_lower or "significant improvements" in snippet_lower:
            findings.append(f"PMID {pmid} reports improvement-related outcomes such as hair regrowth or clinical improvement.")

        if "adverse" in snippet_lower or "safe" in snippet_lower or "well tolerated" in snippet_lower:
            safety_points.append(f"PMID {pmid} includes safety or tolerability language.")

    asks_homeopathy = any(x in query_lower for x in ["homeopathic", "homeopathy", "natural", "herbal", "ayurvedic", "holistic"])
    asks_safety = any(x in query_lower for x in ["safety", "safe", "side effect", "adverse", "risk"])
    asks_teen = any(x in query_lower for x in ["teen", "teenage", "adolescent", "13", "14", "15", "girls"])
    asks_women = any(x in query_lower for x in ["women", "woman", "female", "girls"])

    if asks_homeopathy:
        return (
            "The retrieved evidence does not directly show that homeopathic treatments are effective for alopecia. "
            "The system found alopecia-related biomedical literature, but the retrieved sources focus more on conventional treatments "
            f"such as {', '.join(treatments) if treatments else 'pharmaceutical or diagnostic approaches'} rather than homeopathic interventions. "
            "This means the correct evidence-based conclusion is not that homeopathy works or does not work, but that the retrieved evidence is insufficient to support the claim. "
            "A stronger answer would require studies specifically testing homeopathic treatments in the relevant population and measuring outcomes such as hair regrowth, relapse, safety, and quality of life."
        )

    if asks_safety:
        safety_summary = " ".join(safety_points) if safety_points else "The retrieved evidence contains limited direct safety information."
        return (
            "The retrieved evidence suggests that safety varies by treatment and alopecia type. "
            f"{safety_summary} "
            "For example, the retrieved ritlecitinib evidence mentions mild adverse events such as acne or headache, with one severe anaemia discontinuation noted in the context. "
            "However, the evidence base is not broad enough to compare all alopecia treatments by risk. "
            "A careful safety assessment would need to consider patient age, diagnosis, severity, medical history, and clinician monitoring."
        )

    if asks_teen:
        return (
            "For teenage girls, the retrieved evidence points most clearly to ritlecitinib in severe alopecia areata, because one retrieved source includes patients aged 12 years and older and reports hair-regrowth-related improvement. "
            "However, the system also retrieved evidence about female-pattern hair loss and diagnostic considerations, which may not apply to every teenage patient. "
            "This means the answer depends strongly on the alopecia subtype: alopecia areata, female pattern hair loss, telogen effluvium, and scarring alopecias require different interpretation. "
            "The current evidence is promising but not enough to name one universal best medication for all teenage girls. "
            "A dermatologist would need to match the diagnosis, severity, and safety profile before treatment selection."
        )

    if asks_women and "minoxidil" in treatments:
        return (
            "For women with alopecia, the retrieved evidence highlights minoxidil as relevant to female pattern hair loss, while ritlecitinib appears more connected to severe alopecia areata. "
            "This distinction matters because female pattern hair loss and alopecia areata are different conditions with different treatment logic. "
            "The retrieved evidence supports the idea that treatment choice should be diagnosis-specific rather than based on one general alopecia medication. "
            "Overall, the evidence suggests that minoxidil may be relevant for female pattern hair loss, while JAK-inhibitor evidence may be more relevant for severe alopecia areata. "
            "The best interpretation depends on subtype, severity, and source quality."
        )

    if treatments:
        return (
            f"The retrieved evidence primarily discusses {', '.join(treatments)} in relation to alopecia treatment. "
            "Across the sources, the system found supportive language around improvement, safety, or treatment relevance, but the strength of the conclusion depends on how closely the source matches the user’s question. "
            f"{' '.join(findings) if findings else 'The retrieved snippets provide treatment-related context but limited detailed outcome reporting.'} "
            "The most useful interpretation is that the evidence should be separated by alopecia subtype, patient population, and outcome rather than treated as one general answer. "
            "This platform therefore provides an evidence-grounded synthesis rather than a universal treatment recommendation."
        )

    return (
        "The retrieved evidence is not specific enough to produce a strong treatment conclusion. "
        "The system found alopecia-related literature, but the treatment, population, or outcome may not directly match the question. "
        "This should be interpreted as an evidence gap rather than a positive or negative treatment claim."
    )

def build_advanced_outputs(query, evidence_rows, evidence_direction):
    graded_evidence = build_evidence_grades(evidence_rows)
    claim_audit = build_claim_audit(query, graded_evidence)
    query_type = classify_query(query)

    answer = generate_custom_ai_answer(query, graded_evidence, evidence_direction)

    return {
        "query_type": query_type,
        "answer": answer,
        "graded_evidence": graded_evidence,
        "claim_audit": claim_audit
    }